### ISSUE TITLE
Updater seems to get stuck

### ISSUE THREAD

**Issue by ErisApps** [carina-studio/ULogViewer#14] opened 2022-08-17 09:52 UTC
Whenever there's an update of ULogViewer, the updater seems to get stuck
It only shows the updater icon in the dock and leaving it as-is, doesn't seem to help either. Ended up force-quitting the updater and manually updating during the previous update.
I'm unsure whether this has been broken for a long time or not since I only started using this application recently.

Relevant info (I think):
OS: MacOS Monterey 12.5
Currently installed ULogViewer version: 2.0.3.811
Target ULogViewer version: 2.0.4.815

**Comment by hamster620** [comment] 2022-08-18 00:52
@ErisApps I cannot find the symptom you mentioned by downloading 2.0.3.811 and update to 2.0.4.815 on my MacBook Pro M1 with macOS 12.5.1. We may need your help to check the followings:

1. Make sure that the name of ULogViewer root folder is ```ULogViewer.app```. There are some strange behaviors if the name is incorrect.
2. Make sure that you have moved ```ULogViewer.app``` into your application folder. There are some permission issues if application is not running inside application folder.
3. If you encounter the symptom again, please help to provide the log file stored at ```ULogViewer.app/Contents/MacOS/AutoUpdater-xxxx/AutoUpdater.Avalonia.app/Contents/MacOS/Log```. You can send the log file to [carina.software.studio@gmail.com](mailto:carina.software.studio@gmail.com) if you have any privacy concern about the content of log file.

Thank you.

**Comment by ErisApps** [comment] 2022-08-18 06:17
I'll try double-checking later today.

**Comment by ErisApps** [comment] 2022-08-18 07:03
> 1. Make sure that the name of ULogViewer root folder is `ULogViewer.app`. There are some strange behaviors if the name is incorrect.
> 2. Make sure that you have moved `ULogViewer.app` into your application folder. There are some permission issues if application is not running inside application folder.

I removed (including everything related to it in the downloads folder) and reinstalled the app again and the issue is still reproducible for me.

> 3. If you encounter the symptom again, please help to provide the log file stored at `ULogViewer.app/Contents/MacOS/AutoUpdater-xxxx/AutoUpdater.Avalonia.app/Contents/MacOS/Log`. You can send the log file to [carina.software.studio@gmail.com](mailto:carina.software.studio@gmail.com) if you have any privacy concern about the content of log file.

I'm not exactly sure whether it will be of any help, but please find the AutoUpdater log attached below.
[log.txt](https://github.com/carina-studio/ULogViewer/files/9368358/log.txt)

**Comment by hamster620** [comment] 2022-08-18 11:33
@ErisApps Thanks for providing log. The error was caused by launching auto updater with unsupported language ```en-BE```. Will fix it ASAP.

**Comment by hamster620** [comment] 2022-08-18 13:11
Fixed by [cc7528a](https://github.com/carina-studio/AutoUpdater/commit/cc7528a7911938af8d7e14e261c47fbada285779) and released with [1.1.1.818](https://github.com/carina-studio/AutoUpdater/releases/tag/1.1.1.818).

**Closed by hamster620** 2022-08-18 13:11 UTC
Labels: bug
